/* $Id: tptest.C 79 2007-08-18 17:30:26Z hkoelman $

   Sample Tuxedo client using ATMI++ libray.

 */
#include <algorithm>
#include <string>
#include <cstring>
#include <cstdio>
#include <iostream>
#include <atmi/atmi++.hpp>

using namespace std;
using namespace atmi;

class TPtest : public abstract_client {
  public:

    TPtest () : abstract_client ("tran_test"){
    };

    void run () {

      int ret = -1;

      printf ("%s is starting client program.\n", "herbert");
      printf ("version: %s.\n", atmi::cpp_atmi_version());

      try {

        transaction tp ( "TOUPPER" );
        int urcode = 0;

        try {

          buffer buffer;

          Tfield<string> name ( "EMPNAME" );
          name = (string) "Herbert";

          buffer.add ( &name );

          printf ("Calling service TOUPPER (%s), context: %d.\n", name.c_str() , context());

          try {

            tp.begin();

            //switch ((ret = tp.call ( message, len, (char **)&message, (long *)&len, (int *)&urcode, 1, 1 ))) {
            //switch ((ret = tp.call ( message, len, &message, &len, (int *) NULL, 1, 1 ))) {
            //switch ((ret = tp.call ( message, len, &message, &len ))) {
            //ret = tp.acall ( &buffer );
            //switch ((ret =tp.reply ( &buffer, NULL, &ret))) {

            ret = tp.call ( &buffer );
            switch (ret) {
              case 0:
                break;
              case -1:
                printf ("TOUPPER returned TPFAIL..\n" );
                break;
              default:
                printf ( "TOUPPER returned URCODE: %d (error: %d/%d).\n", ret, tp.error(), tperrno);
                buffer.print();
            }

            buffer.get ( &name );
            printf ( "Call returned: %s.\n", name.c_str() );

            tp.commit();
            printf ("Transcation was committed.\n");
          } catch ( ... ){
            tp.abort();
            printf("Transaction was aborted.\n"); 
            throw;
          }

        } catch ( service_exception& serr ) {
          printf ( "Service Exception catched. tpcall failed..\n" );
          printf ( "What: %s.\n", serr.what () );
        } catch ( tuxedo_exception& err ) {
          printf ( "Tuxedo Exception catched. tpcall failed. %s\n"i, err.what() ); 
          printf ( "What: %s, error detail: %s.\n", err.what () , err.error_detail() );
        };

        printf ( "Ending program." );
      } catch ( tuxedo_exception &err ) {
        printf ( "Tuxedo err: %s.\n" , err.what () );
      } catch (buffer_exception &err ) {
        printf ( "Buffer error: %s.\n",err.what() );
      }

    };
};

int main ( int argc, char **argv ) {

  int ret = 0;

  try {

    TPtest tp;
    tp.run ();

  } catch ( atmi_exception &err ) {
    cerr << err.what () << endl;
  } catch ( std::exception &err ) {
    cerr << err.what() << endl;
  };

  return ret;
}
